version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10007:3001"
    depends_on:
      - postgres
    restart: unless-stopped
  postgres:
    volumes:
      - ./db:/var/lib/postgresql/data
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: basic
      POSTGRES_PASSWORD: 1hgMltrPMF0fJ
      POSTGRES_DB: shortlink
    ports:
      - "10008:5432"
    restart: unless-stopped
