version: "3"
services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3001:3001"
  #   depends_on:
  #     - postgres
  postgres:
    volumes:
      - ./db:/var/lib/postgresql/data
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: basic
      POSTGRES_PASSWORD: 1hgMltrPMF0fJ
      POSTGRES_DB: shortlink
    ports:
      - "5432:5432"
